#!/bin/bash
# ISC License
#
# Copyright (c) 2019-present, Mykhailo Stadnyk <mikhus@gmail.com>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
root_dir="$(readlink -f "$(dirname "$(readlink -f "${0}")")"/..)"
import="$(readlink -f "${root_dir}/scripts")"

red() { echo -e '\033[1;31m'; }
gre() { echo -e '\033[1;32m'; }
yel() { echo -e '\033[1;33m'; }
cya() { echo -e '\033[1;36m'; }
def() { echo -e '\033[0m'; }

# removes any spaces from left and right sides of the string
trim() {
    local s="$*"
    s="${s#"${s%%[![:space:]]*}"}"
    s="${s%"${s##*[![:space:]]}"}"
    echo -n "$s"
}

# joins array by a given separator
# usage join [separator] [array]
join() {
    local d=$1
    shift
    echo -n "$1"
    shift
    printf "%s" "${@/#/$d}"
}

# checks if a given command exists
command_exists() {
    if command -v ${1} >/dev/null 2>&1; then
        return 1
    else
        return 0
    fi
}

spell_check() {
    ${import}/spell "${1}" "${2}"; exit_code=$?

    if [[ ${exit_code} -ne 0 ]]; then
        exit 1
    fi
}
